# Generated by Django 4.0.6 on 2023-06-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
