# Generated by Django 4.0.6 on 2023-06-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=40)),
                ('ccnumber', models.CharField(max_length=40)),
                ('expirymonth', models.CharField(max_length=40)),
                ('expiryyear', models.CharField(max_length=40)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
